version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - cd ./index-photos
      - zip -g deployment_package.zip lambda_function.py
      - cd ..
      - cd ./search-photos
      - zip -g deployment_package1.zip lambda_function.py
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package1.zip
      - echo "DONE!!"
artifacts:
  files:
    - '**/*'
  name: lambdabuiltartifact
  discard-paths: no